### ISSUE TITLE
Deduplication

### ISSUE THREAD

**Issue by nkbt** [babel-plugins/babel-plugin-object-assign#7]
If I compile a project with 100 files and each of them has at least one `Object.assign()`, I will end up with this code repeated 100 times. For each file.
```js
var _extends = Object.assign || function(target) {
  for (var i = 1; i < arguments.length; i++) {
    var source = arguments[i];
    for (var key in source) Object.prototype.hasOwnProperty.call(source, key) && (target[key] = source[key]);
  }
  return target;
}
```

UglifyJS and webpack DedupePlugin cannot handle this unfortunately.

Any ideas?

**Comment by nkbt** [comment]
I could obviously create a separate module like
```js
export default assign = Object.assign
```
or something and import it everywhere, but that does not look like a good solution.

**Comment by nkbt** [comment]
@sebmck, you might find this interesting

**Comment by sebmck** [comment]
Babel already has a couple of features built in to negate this issue:

- [External helpers](https://babeljs.io/docs/advanced/external-helpers/)- instead of adding the helper functions to the top of your file it simply references a global which you can pollute by just including another script.
- [Runtime](https://babeljs.io/docs/usage/runtime/) - instead of adding the helpers functions, it instead imports them from the `babel-runtime` package and references them there so they're only included once.
